# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newgui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 821, 600))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 821, 600))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(320, 340, 451, 201))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.GroupLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.GroupLabel.setObjectName("GroupLabel")
        self.verticalLayout_11.addWidget(self.GroupLabel)
        self.GroupText = QtWidgets.QTextEdit(self.horizontalLayoutWidget_6)
        self.GroupText.setObjectName("GroupText")
        self.verticalLayout_11.addWidget(self.GroupText)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        # self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        # self.verticalLayout_12.setObjectName("verticalLayout_12")
        # self.DriveLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        # self.DriveLabel.setObjectName("DriveLabel")
        # self.verticalLayout_12.addWidget(self.DriveLabel)
        # self.DriveText = QtWidgets.QTextEdit(self.horizontalLayoutWidget_6)
        # self.DriveText.setObjectName("DriveText")
        # self.verticalLayout_12.addWidget(self.DriveText)
        # self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        # self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        # self.verticalLayout_13.setObjectName("verticalLayout_13")
        # self.ProbeLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        # self.ProbeLabel.setObjectName("ProbeLabel")
        # self.verticalLayout_13.addWidget(self.ProbeLabel)
        # self.ProbeText = QtWidgets.QTextEdit(self.horizontalLayoutWidget_6)
        # self.ProbeText.setObjectName("ProbeText")
        # self.verticalLayout_13.addWidget(self.ProbeText)
        # self.horizontalLayout_6.addLayout(self.verticalLayout_13)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 791, 321))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Canvas = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_7)
        self.Canvas.setMaximumSize(QtCore.QSize(300, 300))
        self.Canvas.setObjectName("Canvas")
        self.horizontalLayout_7.addWidget(self.Canvas)
        self.line_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_7)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_7.addWidget(self.line_4)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.line_3 = QtWidgets.QFrame(self.horizontalLayoutWidget_7)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_10.addWidget(self.line_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.STOP = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.STOP.setObjectName("STOP")
        self.verticalLayout_2.addWidget(self.STOP)
        self.load = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.load.setObjectName("load")
        self.verticalLayout_2.addWidget(self.load)
        self.run = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.run.setObjectName("run")
        self.verticalLayout_2.addWidget(self.run)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget_7)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.PositionLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.PositionLabel.setObjectName("PositionLabel")
        self.verticalLayout_9.addWidget(self.PositionLabel)
        self.VelocityLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.VelocityLabel.setObjectName("VelocityLabel")
        self.verticalLayout_9.addWidget(self.VelocityLabel)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ycoordlabel = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.ycoordlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ycoordlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ycoordlabel.setObjectName("ycoordlabel")
        self.gridLayout_2.addWidget(self.ycoordlabel, 0, 1, 1, 1)
        self.zspeedlabel = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.zspeedlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.zspeedlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zspeedlabel.setObjectName("zspeedlabel")
        self.gridLayout_2.addWidget(self.zspeedlabel, 2, 2, 1, 1)
        self.xspeedlabel = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.xspeedlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.xspeedlabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.xspeedlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xspeedlabel.setObjectName("xspeedlabel")
        self.gridLayout_2.addWidget(self.xspeedlabel, 2, 0, 1, 1)
        self.yspeedlabel = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.yspeedlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.yspeedlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yspeedlabel.setObjectName("yspeedlabel")
        self.gridLayout_2.addWidget(self.yspeedlabel, 2, 1, 1, 1)
        self.zcoord = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.zcoord.setObjectName("zcoord")
        self.gridLayout_2.addWidget(self.zcoord, 1, 2, 1, 1)
        self.ycoord = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.ycoord.setObjectName("ycoord")
        self.gridLayout_2.addWidget(self.ycoord, 1, 1, 1, 1)
        self.xspeed = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.xspeed.setObjectName("xspeed")
        self.gridLayout_2.addWidget(self.xspeed, 3, 0, 1, 1)
        self.yspeed = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.yspeed.setObjectName("yspeed")
        self.gridLayout_2.addWidget(self.yspeed, 3, 1, 1, 1)
        self.xcoord = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.xcoord.setObjectName("xcoord")
        self.gridLayout_2.addWidget(self.xcoord, 1, 0, 1, 1)
        self.zspeed = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.zspeed.setObjectName("zspeed")
        self.gridLayout_2.addWidget(self.zspeed, 3, 2, 1, 1)
        self.zcoordlabel = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.zcoordlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.zcoordlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zcoordlabel.setObjectName("zcoordlabel")
        self.gridLayout_2.addWidget(self.zcoordlabel, 0, 2, 1, 1)
        self.xcoordlabel = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.xcoordlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.xcoordlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xcoordlabel.setObjectName("xcoordlabel")
        self.gridLayout_2.addWidget(self.xcoordlabel, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget_7)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.move = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.move.setObjectName("move")
        self.verticalLayout.addWidget(self.move)
        self.set_speed = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.set_speed.setObjectName("set_speed")
        self.verticalLayout.addWidget(self.set_speed)
        self.zero = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.zero.setObjectName("zero")
        self.verticalLayout.addWidget(self.zero)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 791, 551))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(320, 340, 451, 201))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.GroupLabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.GroupLabel_2.setObjectName("GroupLabel_2")
        self.verticalLayout_14.addWidget(self.GroupLabel_2)
        self.GroupText_2 = QtWidgets.QTextEdit(self.horizontalLayoutWidget_8)
        self.GroupText_2.setObjectName("GroupText_2")
        self.verticalLayout_14.addWidget(self.GroupText_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.DriveLabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.DriveLabel_2.setObjectName("DriveLabel_2")
        self.verticalLayout_15.addWidget(self.DriveLabel_2)
        self.DriveText_2 = QtWidgets.QTextEdit(self.horizontalLayoutWidget_8)
        self.DriveText_2.setObjectName("DriveText_2")
        self.verticalLayout_15.addWidget(self.DriveText_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.ProbeLabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.ProbeLabel_2.setObjectName("ProbeLabel_2")
        self.verticalLayout_16.addWidget(self.ProbeLabel_2)
        self.ProbeText_2 = QtWidgets.QTextEdit(self.horizontalLayoutWidget_8)
        self.ProbeText_2.setObjectName("ProbeText_2")
        self.verticalLayout_16.addWidget(self.ProbeText_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_16)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(0, 0, 791, 321))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Canvas_2 = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_9)
        self.Canvas_2.setMaximumSize(QtCore.QSize(300, 300))
        self.Canvas_2.setObjectName("Canvas_2")
        self.horizontalLayout_9.addWidget(self.Canvas_2)
        self.line_5 = QtWidgets.QFrame(self.horizontalLayoutWidget_9)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_9.addWidget(self.line_5)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.line_6 = QtWidgets.QFrame(self.horizontalLayoutWidget_9)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_17.addWidget(self.line_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.STOP_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.STOP_2.setObjectName("STOP_2")
        self.verticalLayout_3.addWidget(self.STOP_2)
        self.load_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.load_2.setObjectName("load_2")
        self.verticalLayout_3.addWidget(self.load_2)
        self.run_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.run_2.setObjectName("run_2")
        self.verticalLayout_3.addWidget(self.run_2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.line_7 = QtWidgets.QFrame(self.horizontalLayoutWidget_9)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_10.addWidget(self.line_7)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.PositionLabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.PositionLabel_2.setObjectName("PositionLabel_2")
        self.verticalLayout_18.addWidget(self.PositionLabel_2)
        self.VelocityLabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.VelocityLabel_2.setObjectName("VelocityLabel_2")
        self.verticalLayout_18.addWidget(self.VelocityLabel_2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_18)
        self.verticalLayout_17.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ycoordlabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.ycoordlabel_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ycoordlabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ycoordlabel_2.setObjectName("ycoordlabel_2")
        self.gridLayout_3.addWidget(self.ycoordlabel_2, 0, 1, 1, 1)
        self.zspeedlabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.zspeedlabel_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.zspeedlabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.zspeedlabel_2.setObjectName("zspeedlabel_2")
        self.gridLayout_3.addWidget(self.zspeedlabel_2, 2, 2, 1, 1)
        self.xspeedlabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.xspeedlabel_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.xspeedlabel_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.xspeedlabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.xspeedlabel_2.setObjectName("xspeedlabel_2")
        self.gridLayout_3.addWidget(self.xspeedlabel_2, 2, 0, 1, 1)
        self.yspeedlabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.yspeedlabel_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.yspeedlabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.yspeedlabel_2.setObjectName("yspeedlabel_2")
        self.gridLayout_3.addWidget(self.yspeedlabel_2, 2, 1, 1, 1)
        self.zcoord_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.zcoord_2.setObjectName("zcoord_2")
        self.gridLayout_3.addWidget(self.zcoord_2, 1, 2, 1, 1)
        self.ycoord_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.ycoord_2.setObjectName("ycoord_2")
        self.gridLayout_3.addWidget(self.ycoord_2, 1, 1, 1, 1)
        self.xspeed_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.xspeed_2.setObjectName("xspeed_2")
        self.gridLayout_3.addWidget(self.xspeed_2, 3, 0, 1, 1)
        self.yspeed_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.yspeed_2.setObjectName("yspeed_2")
        self.gridLayout_3.addWidget(self.yspeed_2, 3, 1, 1, 1)
        self.xcoord_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.xcoord_2.setObjectName("xcoord_2")
        self.gridLayout_3.addWidget(self.xcoord_2, 1, 0, 1, 1)
        self.zspeed_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.zspeed_2.setObjectName("zspeed_2")
        self.gridLayout_3.addWidget(self.zspeed_2, 3, 2, 1, 1)
        self.zcoordlabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.zcoordlabel_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.zcoordlabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.zcoordlabel_2.setObjectName("zcoordlabel_2")
        self.gridLayout_3.addWidget(self.zcoordlabel_2, 0, 2, 1, 1)
        self.xcoordlabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.xcoordlabel_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.xcoordlabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.xcoordlabel_2.setObjectName("xcoordlabel_2")
        self.gridLayout_3.addWidget(self.xcoordlabel_2, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.line_8 = QtWidgets.QFrame(self.horizontalLayoutWidget_9)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_2.addWidget(self.line_8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.move_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.move_2.setObjectName("move_2")
        self.verticalLayout_4.addWidget(self.move_2)
        self.set_speed_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.set_speed_2.setObjectName("set_speed_2")
        self.verticalLayout_4.addWidget(self.set_speed_2)
        self.zero_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.zero_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.zero_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_17.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_17)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GroupLabel.setText(_translate("MainWindow", "Group Information"))
        # self.DriveLabel.setText(_translate("MainWindow", "Drive Information"))
        # self.ProbeLabel.setText(_translate("MainWindow", "Probe Information"))
        self.STOP.setText(_translate("MainWindow", "STOP MOVEMENT"))
        self.load.setText(_translate("MainWindow", "LOAD GROUP CONFIGURATION"))
        self.run.setText(_translate("MainWindow", "RUN CONFIGURATION"))
        self.PositionLabel.setText(_translate("MainWindow", "CURRENT PROBE POSITION"))
        self.VelocityLabel.setText(_translate("MainWindow", "CURRENT MOTOR VELOCITY"))
        self.ycoordlabel.setText(_translate("MainWindow", "Y-COORDINATE"))
        self.zspeedlabel.setText(_translate("MainWindow", "Z-SPEED"))
        self.xspeedlabel.setText(_translate("MainWindow", "X-SPEED"))
        self.yspeedlabel.setText(_translate("MainWindow", "Y-SPEED"))
        self.zcoordlabel.setText(_translate("MainWindow", "Z-COORDINATE"))
        self.xcoordlabel.setText(_translate("MainWindow", " X-COORDINATE"))
        self.move.setText(_translate("MainWindow", "Move"))
        self.set_speed.setText(_translate("MainWindow", "Set Speed"))
        self.zero.setText(_translate("MainWindow", "Set Zero"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.GroupLabel_2.setText(_translate("MainWindow", "Group Information"))
        self.DriveLabel_2.setText(_translate("MainWindow", "Drive Information"))
        self.ProbeLabel_2.setText(_translate("MainWindow", "Probe Information"))
        self.STOP_2.setText(_translate("MainWindow", "STOP MOVEMENT"))
        self.load_2.setText(_translate("MainWindow", "LOAD GROUP CONFIGURATION"))
        self.run_2.setText(_translate("MainWindow", "RUN CONFIGURATION"))
        self.PositionLabel_2.setText(_translate("MainWindow", "CURRENT PROBE POSITION"))
        self.VelocityLabel_2.setText(_translate("MainWindow", "CURRENT MOTOR VELOCITY"))
        self.ycoordlabel_2.setText(_translate("MainWindow", "Y-COORDINATE"))
        self.zspeedlabel_2.setText(_translate("MainWindow", "Z-SPEED"))
        self.xspeedlabel_2.setText(_translate("MainWindow", "X-SPEED"))
        self.yspeedlabel_2.setText(_translate("MainWindow", "Y-SPEED"))
        self.zcoordlabel_2.setText(_translate("MainWindow", "Z-COORDINATE"))
        self.xcoordlabel_2.setText(_translate("MainWindow", " X-COORDINATE"))
        self.move_2.setText(_translate("MainWindow", "Move"))
        self.set_speed_2.setText(_translate("MainWindow", "Set Speed"))
        self.zero_2.setText(_translate("MainWindow", "Set Zero"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

